version: '3'

services:
  app:
    build: .
    command: 'mix phx.server'
    ports:
      - '4000:4000'
    volumes:
      - '.:/app'
    environment:
      MIX_ENV: 'dev'
      PORT: '4000'
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: 'postgres:11.3-alpine'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - 'db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  adminer:
    image: 'adminer:4.6.3'
    ports:
      - '8081:8080'

volumes:
  db:
